title: Kevin Slote # your name (or website title) here
logo: "/images/me2.jpg?raw=true" # your photo (or logo) here
description: >
  Research Fellow Clarkson University </br>
  Ph.D. Georgia State University </br>
  Pure Math: Algebraic Geometry masters degree. </br>
  Generative AI: Transformers, LLMs. </br>
  Math: computational topology, dynamical systems, causal models. </br>

  <br><br>
  <a href="www.linkedin.com/in/kevin-slote">LinkedIn Profile</a> </br>
  <a href="https://math.stackexchange.com/users/95560/kslote1">Mathoverflow Profile</a></br>
  <a href="https://sites.google.com/view/kevin-slote">Academic Professional Website</a></br>
  <a href="https://twitter.com/kslote1">Twitter</a></br>
  <a href="https://medium.com/@kslote1">Medium</a></br>
  <a href="https://scholar.google.com/citations?user=Otx9t8IAAAAJ&hl=en">Google Scholar</a></br>
  <a href="https://www.kevin-slote.com/">Website</a></br>
   <a href="https://huggingface.co/kslote/">Huggingface 🤗</a></br>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Kevin Slote",
  "givenName": "Kevin",
  "familyName": "Slote",
  "jobTitle": "Postdoctoral Researcher",
  "affiliation": {
    "@type": "CollegeOrUniversity",
    "name": "Clarkson University",
    "url": "https://www.clarkson.edu/"
  },
  "alumniOf": {
    "@type": "CollegeOrUniversity",
    "name": "Georgia State University",
    "url": "https://www.gsu.edu/"
  },
  "url": "https://www.kevin-slote.com",
  "sameAs": [
    "https://www.wikidata.org/wiki/Q125511795",
    "https://orcid.org/0000-0002-XXXX-YYYY",
    "https://scholar.google.com/citations?user=XXXX",
    "https://github.com/kslote1",
    "https://www.linkedin.com/in/kevin-slote",
    "https://www.youtube.com/@KevinSloteMathResearch"
  ],
  "identifier": {
    "@type": "PropertyValue",
    "propertyID": "Wikidata",
    "value": "Q125511795",
    "url": "https://www.wikidata.org/wiki/Q125511795"
  },
  "knowsAbout": [
    "Applied Mathematics",
    "Causality",
    "Neuroscience",
    "Machine Learning",
    "Topology",
    "Dynamical Systems"
  ]
}
</script>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
